import axiosInstance from '../api/axiosInstance';
import { PETITION_ENDPOINTS } from '../constants/apiEndpoints';

class PetitionApiService {
  // Submit a new petition
  async submitPetition(petitionData) {
    try {
      const response = await axiosInstance.post(PETITION_ENDPOINTS.SUBMIT_PETITION, petitionData);
      return response.data;
    } catch (error) {
      console.error('Error submitting petition:', error);
      throw error;
    }
  }

  // Get petitions by organization ID
  async getPetitionsByOrganization(organizationId) {
    try {
      const response = await axiosInstance.get(PETITION_ENDPOINTS.GET_PETITIONS_BY_ORGANIZATION(organizationId));
      return response.data;
    } catch (error) {
      console.error('Error fetching petitions by organization:', error);
      throw error;
    }
  }

  // Get paginated petitions by organization ID with filters
  async getPetitionsPaged(paginationParams) {
    try {
      console.log('API Service - Sending request to:', PETITION_ENDPOINTS.GET_PETITIONS_PAGED);
      console.log('API Service - Request body:', paginationParams);
      
      // Ensure all required parameters are present and valid
      const validatedParams = {
        organizationId: paginationParams.organizationId,
        pageNumber: paginationParams.pageNumber || 1, // Default to page 1 (1-based)
        pageSize: paginationParams.pageSize || 5,
        searchText: paginationParams.searchText || "",
        status: paginationParams.status || 0,
        fromDate: paginationParams.fromDate,
        toDate: paginationParams.toDate,
        sortBy: paginationParams.sortBy || 'filingDate',
        sortOrder: paginationParams.sortOrder || 'desc'
      };
      
      console.log('API Service - Validated params:', validatedParams);
      console.log('API Service - Base URL:', axiosInstance.defaults.baseURL);
      console.log('API Service - Endpoint:', PETITION_ENDPOINTS.GET_PETITIONS_PAGED);
      console.log('API Service - Full URL:', axiosInstance.defaults.baseURL + PETITION_ENDPOINTS.GET_PETITIONS_PAGED);
      
      const response = await axiosInstance.post(PETITION_ENDPOINTS.GET_PETITIONS_PAGED, validatedParams, {
        headers: {
          'Accept': 'text/plain',
          'Content-Type': 'application/json'
        }
      });
      console.log('API Service - Response:', response.data);
      return response.data;
    } catch (error) {
      console.error('Error fetching paginated petitions:', error);
      console.error('Error response:', error.response?.data);
      throw error;
    }
  }

  // Transform form data to API format
  transformFormDataToApiFormat(formData, organizationId) {
    // Helper function to safely convert dates
    const safeDateConversion = (dateString) => {
      if (!dateString) return null;
      try {
        const date = new Date(dateString);
        return isNaN(date.getTime()) ? null : date.toISOString();
      } catch (error) {
        console.error('Date conversion error:', error);
        return null;
      }
    };

    
    const petitionData = {
      organizationId: organizationId,
      duplicateHash: "", // This will be generated by the backend
      property: {
        propertyStreet1: formData.propertyStreet1 || "",
        propertyStreet2: formData.propertyStreet2 || "",
        propertyCity: formData.propertyCity || "",
        propertyState: formData.propertyState || "MA",
        propertyZip: formData.propertyZip || "",
        propertyCounty: formData.propertyCounty || "",
        assessorParcelId: formData.assessorParcelId || ""
      },
      loan: {
        minNumber: formData.minNumber || "",
        loanNumber: formData.loanNumber || "",
        petitionLoanTypeId: formData.petitionLoanTypeId && formData.petitionLoanTypeId.trim() !== '' ? formData.petitionLoanTypeId : null,
        petitionLoanTypeName: formData.petitionLoanTypeName || "",
        lienPosition: parseInt(formData.lienPosition) || 0,
        originationDate: safeDateConversion(formData.originationDate),
        originalPrincipalAmount: parseFloat(formData.originalPrincipalAmount) || 0,
        currentPrincipalBalance: parseFloat(formData.currentPrincipalBalance) || 0,
        interestRatePercent: parseFloat(formData.interestRatePercent) || 0,
        variableRate: formData.variableRate || false,
        interestOnly: formData.interestOnly || false,
        negativeAmortization: formData.negativeAmortization || false,
        monthlyPaymentAmount: parseFloat(formData.monthlyPaymentAmount) || 0,
        delinquencyDaysAtFiling: parseInt(formData.delinquencyDaysAtFiling) || 0
      },
      rightToCure: {
        noticeSent: formData.noticeSent || false,
        noticeDate: safeDateConversion(formData.noticeDate),
        amountInDefault: parseFloat(formData.amountInDefault) || 0,
        daysDelinquentAtNotice: parseInt(formData.daysDelinquentAtNotice) || 0,
        cureExpirationDate: safeDateConversion(formData.cureExpirationDate),
        noticeAddressStreet1: formData.noticeAddressStreet1 || "",
        noticeAddressCity: formData.noticeAddressCity || "",
        noticeAddressState: formData.noticeAddressState || "",
        noticeAddressZip: formData.noticeAddressZip || "",
        manualOverrideReason: formData.manualOverrideReason || ""
      },
      affidavit: {
        certainMortgageLoan: formData.certainMortgageLoan || false,
        form35bComplianceAffidavitPdf: formData.form35bComplianceAffidavitPdf || "",
        form35bNonApplicabilityAffidavitPdf: formData.form35bNonApplicabilityAffidavitPdf || "",
        affiantName: formData.affiantName || "",
        affiantTitle: formData.affiantTitle || "",
        affidavitExecutionDate: safeDateConversion(formData.affidavitExecutionDate)
      },
      filingEntity: {
        filingEntityLegalName: formData.filingEntityLegalName || "",
        filingEntityRole: parseInt(formData.filingEntityRole) || 0,
        filingEntityStreet1: formData.filingEntityStreet1 || "",
        filingEntityCity: formData.filingEntityCity || "",
        filingEntityState: formData.filingEntityState || "",
        filingEntityZip: formData.filingEntityZip || "",
        filingContactName: formData.filingContactName || "",
        filingContactEmail: formData.filingContactEmail || "",
        filingContactPhone: formData.filingContactPhone || "",
        nmlsLicenseNumber: formData.nmlsLicenseNumber || "",
        stateLicenseNumber: formData.stateLicenseNumber || "",
        stateLicenseState: formData.stateLicenseState || ""
      },
      signatures: (formData.signatures || []).map(signature => ({
        ...signature,
        signedAt: safeDateConversion(signature.signedAt)
      })),
      borrowers: (formData.borrowers || []).map(borrower => ({
        firstName: borrower.firstName,
        middleName: borrower.middleName,
        lastName: borrower.lastName,
        suffix: borrower.suffix,
        borrowerIsPrimary: borrower.borrowerIsPrimary,
        mailingStreet1: borrower.mailingStreet1,
        mailingCity: borrower.mailingCity,
        mailingState: borrower.mailingState,
        mailingZip: borrower.mailingZip,
        phone: borrower.phone,
        email: borrower.email
      })),
      loanAssignees: (formData.loanAssignees || []).map(assignee => ({
        ...assignee,
        assigneeTypeId: assignee.assigneeTypeId && assignee.assigneeTypeId.trim() !== '' ? assignee.assigneeTypeId : null,
        assigneeRoleId: assignee.assigneeRoleId && assignee.assigneeRoleId.trim() !== '' ? assignee.assigneeRoleId : null
      })),
      documents: (formData.documents || []).map(document => ({
        ...document,
        uploadedOn: safeDateConversion(document.uploadedOn)
      }))
    };

    // Send data directly as dto parameter (not wrapped in object)
    return petitionData;
  }

  // Transform API response to display format
  transformApiResponseToDisplayFormat(apiResponse) {
    if (!apiResponse || !apiResponse.data) {
      return [];
    }

    console.log('Transforming API response:', apiResponse);
    // Handle both single petition and array of petitions
    const petitions = Array.isArray(apiResponse.data) ? apiResponse.data : [apiResponse.data];
    console.log('Petitions to transform:', petitions);

    const transformedPetitions = petitions.map(petition => {
      // Map status number to readable status
      const getStatusDisplay = (status) => {
        switch (status) {
          case "0": return { text: "Draft", class: "Draft" };
          case "1": return { text: "Submitted", class: "Submitted" };
          case "2": return { text: "Returned", class: "Returned" };
          case "3": return { text: "Resubmitted", class: "Resubmitted" };
          case "4": return { text: "Accepted", class: "Accepted" };
          case "5": return { text: "Closed", class: "Closed" };
          default: return { text: "Unknown", class: "Unknown" };
        }
      };

      const statusInfo = getStatusDisplay(petition.status);

      // Get borrower name from the first borrower
      let borrowerName = 'N/A';
      if (petition.borrowers && petition.borrowers.length > 0) {
        const borrower = petition.borrowers[0];
        const nameParts = [borrower.firstName, borrower.middleName, borrower.lastName, borrower.suffix]
          .filter(part => part && part.trim())
          .map(part => part.trim());
        borrowerName = nameParts.join(' ') || 'N/A';
      }

      // Format loan amount
      let loanAmount = 'N/A';
      if (petition.loan?.currentPrincipalBalance) {
        loanAmount = `$${parseFloat(petition.loan.currentPrincipalBalance).toLocaleString()}`;
      } else if (petition.loan?.originalPrincipalAmount) {
        loanAmount = `$${parseFloat(petition.loan.originalPrincipalAmount).toLocaleString()}`;
      }

      // Format property address
      const addressParts = [
        petition.property?.propertyStreet1,
        petition.property?.propertyStreet2,
        petition.property?.propertyCity,
        petition.property?.propertyState,
        petition.property?.propertyZip
      ].filter(part => part && part.trim());
      const propertyAddress = addressParts.join(', ') || 'N/A';

      return {
        id: petition.id,
        petitionNumber: petition.petitionNumber || 'N/A',
        propertyAddress,
        status: statusInfo.text,
        statusClass: statusInfo.class,
        statusValue: petition.status,
        filingDate: petition.createdDate ? new Date(petition.createdDate).toLocaleDateString() : new Date().toLocaleDateString(),
        lastUpdated: petition.modifiedDate ? new Date(petition.modifiedDate).toLocaleString('en-US', { 
          year: 'numeric', 
          month: '2-digit', 
          day: '2-digit', 
          hour: '2-digit', 
          minute: '2-digit', 
          hour12: true 
        }) : new Date().toLocaleString('en-US', { 
          year: 'numeric', 
          month: '2-digit', 
          day: '2-digit', 
          hour: '2-digit', 
          minute: '2-digit', 
          hour12: true 
        }),
        borrower: borrowerName,
        loanAmount,
        county: petition.property?.propertyCounty || 'N/A',
        details: petition // Store full details for modal view
      };
    });
    
    console.log('Transformed petitions:', transformedPetitions);
    return transformedPetitions;
  }
}

// Create and export a singleton instance
const petitionApiService = new PetitionApiService();

export default petitionApiService;
