import axiosInstance from '../api/axiosInstance';
import { PETITION_ENDPOINTS } from '../constants/apiEndpoints';

class PetitionApiService {
  // Submit a new petition
  async submitPetition(petitionData) {
    try {
      const response = await axiosInstance.post(PETITION_ENDPOINTS.SUBMIT_PETITION, petitionData);
      return response.data;
    } catch (error) {
      console.error('Error submitting petition:', error);
      throw error;
    }
  }

  // Get petitions by organization ID
  async getPetitionsByOrganization(organizationId) {
    try {
      const response = await axiosInstance.get(PETITION_ENDPOINTS.GET_PETITIONS_BY_ORGANIZATION(organizationId));
      return response.data;
    } catch (error) {
      console.error('Error fetching petitions by organization:', error);
      throw error;
    }
  }

  // Transform form data to API format
  transformFormDataToApiFormat(formData, organizationId) {
    return {
      organizationId: organizationId,
      duplicateHash: "", // This will be generated by the backend
      property: {
        propertyStreet1: formData.propertyStreet1 || "",
        propertyStreet2: formData.propertyStreet2 || "",
        propertyCity: formData.propertyCity || "",
        propertyState: formData.propertyState || "MA",
        propertyZip: formData.propertyZip || "",
        propertyCounty: formData.propertyCounty || "",
        assessorParcelId: formData.assessorParcelId || ""
      },
      loan: {
        minNumber: formData.minNumber || "",
        loanNumber: formData.loanNumber || "",
        petitionLoanTypeId: formData.petitionLoanTypeId || "",
        petitionLoanTypeName: formData.petitionLoanTypeName || "",
        lienPosition: parseInt(formData.lienPosition) || 0,
        originationDate: formData.originationDate ? new Date(formData.originationDate).toISOString() : "",
        originalPrincipalAmount: parseFloat(formData.originalPrincipalAmount) || 0,
        currentPrincipalBalance: parseFloat(formData.currentPrincipalBalance) || 0,
        interestRatePercent: parseFloat(formData.interestRatePercent) || 0,
        variableRate: formData.variableRate || false,
        interestOnly: formData.interestOnly || false,
        negativeAmortization: formData.negativeAmortization || false,
        monthlyPaymentAmount: parseFloat(formData.monthlyPaymentAmount) || 0,
        delinquencyDaysAtFiling: parseInt(formData.delinquencyDaysAtFiling) || 0
      },
      rightToCure: {
        noticeSent: formData.noticeSent || false,
        noticeDate: formData.noticeDate ? new Date(formData.noticeDate).toISOString() : "",
        amountInDefault: parseFloat(formData.amountInDefault) || 0,
        daysDelinquentAtNotice: parseInt(formData.daysDelinquentAtNotice) || 0,
        cureExpirationDate: formData.cureExpirationDate ? new Date(formData.cureExpirationDate).toISOString() : "",
        noticeAddressStreet1: formData.noticeAddressStreet1 || "",
        noticeAddressCity: formData.noticeAddressCity || "",
        noticeAddressState: formData.noticeAddressState || "",
        noticeAddressZip: formData.noticeAddressZip || "",
        manualOverrideReason: formData.manualOverrideReason || ""
      },
      affidavit: {
        certainMortgageLoan: formData.certainMortgageLoan || false,
        form35bComplianceAffidavitPdf: formData.form35bComplianceAffidavitPdf || "",
        form35bNonApplicabilityAffidavitPdf: formData.form35bNonApplicabilityAffidavitPdf || "",
        affiantName: formData.affiantName || "",
        affiantTitle: formData.affiantTitle || "",
        affidavitExecutionDate: formData.affidavitExecutionDate ? new Date(formData.affidavitExecutionDate).toISOString() : ""
      },
      filingEntity: {
        filingEntityLegalName: formData.filingEntityLegalName || "",
        filingEntityRole: parseInt(formData.filingEntityRole) || 0,
        filingEntityStreet1: formData.filingEntityStreet1 || "",
        filingEntityCity: formData.filingEntityCity || "",
        filingEntityState: formData.filingEntityState || "",
        filingEntityZip: formData.filingEntityZip || "",
        filingContactName: formData.filingContactName || "",
        filingContactEmail: formData.filingContactEmail || "",
        filingContactPhone: formData.filingContactPhone || "",
        nmlsLicenseNumber: formData.nmlsLicenseNumber || "",
        stateLicenseNumber: formData.stateLicenseNumber || "",
        stateLicenseState: formData.stateLicenseState || ""
      },
      signatures: formData.signatures || [],
      borrowers: formData.borrowers || [],
      loanAssignees: formData.loanAssignees || [],
      documents: formData.documents || []
    };
  }

  // Transform API response to display format
  transformApiResponseToDisplayFormat(apiResponse) {
    if (!apiResponse || !apiResponse.data) {
      return [];
    }

    // Handle both single petition and array of petitions
    const petitions = Array.isArray(apiResponse.data) ? apiResponse.data : [apiResponse.data];

    return petitions.map(petition => {
      // Map status number to readable status
      const getStatusDisplay = (status) => {
        switch (status) {
          case "0": return { text: "Draft", class: "Draft" };
          case "1": return { text: "Submitted", class: "Submitted" };
          case "2": return { text: "Returned", class: "Returned" };
          case "3": return { text: "Resubmitted", class: "Resubmitted" };
          case "4": return { text: "Accepted", class: "Accepted" };
          case "5": return { text: "Closed", class: "Closed" };
          default: return { text: "Unknown", class: "Unknown" };
        }
      };

      const statusInfo = getStatusDisplay(petition.status);

      // Get borrower name from the first borrower
      let borrowerName = 'N/A';
      if (petition.borrowers && petition.borrowers.length > 0) {
        const borrower = petition.borrowers[0];
        const nameParts = [borrower.firstName, borrower.middleName, borrower.lastName, borrower.suffix]
          .filter(part => part && part.trim())
          .map(part => part.trim());
        borrowerName = nameParts.join(' ') || 'N/A';
      }

      // Format loan amount
      let loanAmount = 'N/A';
      if (petition.loan?.currentPrincipalBalance) {
        loanAmount = `$${parseFloat(petition.loan.currentPrincipalBalance).toLocaleString()}`;
      } else if (petition.loan?.originalPrincipalAmount) {
        loanAmount = `$${parseFloat(petition.loan.originalPrincipalAmount).toLocaleString()}`;
      }

      // Format property address
      const addressParts = [
        petition.property?.propertyStreet1,
        petition.property?.propertyStreet2,
        petition.property?.propertyCity,
        petition.property?.propertyState,
        petition.property?.propertyZip
      ].filter(part => part && part.trim());
      const propertyAddress = addressParts.join(', ') || 'N/A';

      return {
        id: petition.id,
        petitionNumber: petition.petitionNumber || 'N/A',
        propertyAddress,
        status: statusInfo.text,
        statusClass: statusInfo.class,
        statusValue: petition.status,
        filingDate: petition.createdAt || new Date().toISOString().split('T')[0],
        lastUpdated: petition.updatedAt || new Date().toISOString(),
        borrower: borrowerName,
        loanAmount,
        county: petition.property?.propertyCounty || 'N/A',
        details: petition // Store full details for modal view
      };
    });
  }
}

// Create and export a singleton instance
const petitionApiService = new PetitionApiService();

export default petitionApiService;
