import axiosInstance from '../api/axiosInstance';
import { PETITION_ENDPOINTS } from '../constants/apiEndpoints';

class PetitionApiService {
  // Submit a new petition
  async submitPetition(petitionData) {
    try {
      const response = await axiosInstance.post(PETITION_ENDPOINTS.SUBMIT_PETITION, petitionData);
      return response.data;
    } catch (error) {
      console.error('Error submitting petition:', error);
      throw error;
    }
  }

  // Get petitions by organization ID
  async getPetitionsByOrganization(organizationId) {
    try {
      const response = await axiosInstance.get(PETITION_ENDPOINTS.GET_PETITIONS_BY_ORGANIZATION(organizationId));
      return response.data;
    } catch (error) {
      console.error('Error fetching petitions by organization:', error);
      throw error;
    }
  }

  // Transform form data to API format
  transformFormDataToApiFormat(formData, organizationId) {
    return {
      organizationId: organizationId,
      duplicateHash: "", // This will be generated by the backend
      property: {
        propertyStreet1: formData.propertyStreet1 || "",
        propertyStreet2: formData.propertyStreet2 || "",
        propertyCity: formData.propertyCity || "",
        propertyState: formData.propertyState || "MA",
        propertyZip: formData.propertyZip || "",
        propertyCounty: formData.propertyCounty || "",
        assessorParcelId: formData.assessorParcelId || ""
      },
      loan: {
        minNumber: formData.minNumber || "",
        loanNumber: formData.loanNumber || "",
        petitionLoanTypeId: formData.petitionLoanTypeId || "",
        petitionLoanTypeName: formData.petitionLoanTypeName || "",
        lienPosition: parseInt(formData.lienPosition) || 0,
        originationDate: formData.originationDate ? new Date(formData.originationDate).toISOString() : "",
        originalPrincipalAmount: parseFloat(formData.originalPrincipalAmount) || 0,
        currentPrincipalBalance: parseFloat(formData.currentPrincipalBalance) || 0,
        interestRatePercent: parseFloat(formData.interestRatePercent) || 0,
        variableRate: formData.variableRate || false,
        interestOnly: formData.interestOnly || false,
        negativeAmortization: formData.negativeAmortization || false,
        monthlyPaymentAmount: parseFloat(formData.monthlyPaymentAmount) || 0,
        delinquencyDaysAtFiling: parseInt(formData.delinquencyDaysAtFiling) || 0
      },
      rightToCure: {
        noticeSent: formData.noticeSent || false,
        noticeDate: formData.noticeDate ? new Date(formData.noticeDate).toISOString() : "",
        amountInDefault: parseFloat(formData.amountInDefault) || 0,
        daysDelinquentAtNotice: parseInt(formData.daysDelinquentAtNotice) || 0,
        cureExpirationDate: formData.cureExpirationDate ? new Date(formData.cureExpirationDate).toISOString() : "",
        noticeAddressStreet1: formData.noticeAddressStreet1 || "",
        noticeAddressCity: formData.noticeAddressCity || "",
        noticeAddressState: formData.noticeAddressState || "",
        noticeAddressZip: formData.noticeAddressZip || "",
        manualOverrideReason: formData.manualOverrideReason || ""
      },
      affidavit: {
        certainMortgageLoan: formData.certainMortgageLoan || false,
        form35bComplianceAffidavitPdf: formData.form35bComplianceAffidavitPdf || "",
        form35bNonApplicabilityAffidavitPdf: formData.form35bNonApplicabilityAffidavitPdf || "",
        affiantName: formData.affiantName || "",
        affiantTitle: formData.affiantTitle || "",
        affidavitExecutionDate: formData.affidavitExecutionDate ? new Date(formData.affidavitExecutionDate).toISOString() : ""
      },
      filingEntity: {
        filingEntityLegalName: formData.filingEntityLegalName || "",
        filingEntityRole: parseInt(formData.filingEntityRole) || 0,
        filingEntityStreet1: formData.filingEntityStreet1 || "",
        filingEntityCity: formData.filingEntityCity || "",
        filingEntityState: formData.filingEntityState || "",
        filingEntityZip: formData.filingEntityZip || "",
        filingContactName: formData.filingContactName || "",
        filingContactEmail: formData.filingContactEmail || "",
        filingContactPhone: formData.filingContactPhone || "",
        nmlsLicenseNumber: formData.nmlsLicenseNumber || "",
        stateLicenseNumber: formData.stateLicenseNumber || "",
        stateLicenseState: formData.stateLicenseState || ""
      },
      signatures: formData.signatures || [],
      borrowers: formData.borrowers || [],
      loanAssignees: formData.loanAssignees || [],
      documents: formData.documents || []
    };
  }

  // Transform API response to display format
  transformApiResponseToDisplayFormat(apiResponse) {
    if (!apiResponse || !apiResponse.data) {
      return [];
    }

    // Handle both single petition and array of petitions
    const petitions = Array.isArray(apiResponse.data) ? apiResponse.data : [apiResponse.data];

    return petitions.map(petition => ({
      id: petition.id || petition.petitionNumber || 'N/A',
      petitionNumber: petition.petitionNumber || 'N/A',
      propertyAddress: `${petition.property?.propertyStreet1 || ''}, ${petition.property?.propertyCity || ''}, ${petition.property?.propertyState || ''} ${petition.property?.propertyZip || ''}`,
      status: petition.status || 'Unknown',
      filingDate: petition.createdAt || new Date().toISOString().split('T')[0],
      lastUpdated: petition.updatedAt || new Date().toISOString(),
      borrower: petition.borrowers && petition.borrowers.length > 0 
        ? `${petition.borrowers[0].firstName || ''} ${petition.borrowers[0].lastName || ''}`.trim() 
        : 'N/A',
      loanAmount: petition.loan?.currentPrincipalBalance 
        ? `$${parseFloat(petition.loan.currentPrincipalBalance).toLocaleString()}` 
        : 'N/A',
      county: petition.property?.propertyCounty || 'N/A',
      details: petition // Store full details for modal view
    }));
  }
}

// Create and export a singleton instance
const petitionApiService = new PetitionApiService();

export default petitionApiService;
