export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  ORGANIZATIONS: '/organizations',
  PROFILE: '/profile',
  PETITIONS: '/petitions',
  PUBLIC_PETITIONS: '/public-petitions',
  MESSAGES: '/messages',
  FAQ: '/faq',
  TRAINING: '/training',
  FORM35: '/form35',
  ORGANIZATION_JOIN_REQUESTS: '/organization-join-requests',
    ORGANISATION_USERS: '/organisation-users',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  PASSWORD_EMAIL_SENT: '/password-email-sent',
  SET_NEW_PASSWORD: '/set-new-password',
  PASSWORD_CHANGED: '/password-changed',
  TWO_FACTOR_AUTH: '/two-factor-auth',
  VERIFICATION_PAGE: '/verification-page',
  VERIFICATION_EMAIL_SENT: '/verification-email-sent',
  REQUEST_IMPERSONATE_USER: '/request-impersonate-user',
  NOT_FOUND: '*',
};
